"""create ticketing tables

Revision ID: 47e7f5a8fac0
Revises: ce18733dbbd6
Create Date: 2026-10-03 07:03:09.933808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47e7f5a8fac0'
down_revision: Union[str, Sequence[str], None] = 'ce18733dbbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

customer_urgency_enum = postgresql.ENUM(
    "NORMAL", "URGENT",
    name="customer_urgency",
    create_type=False,
)

ticket_priority_enum = postgresql.ENUM(
    "LOW", "MEDIUM", "HIGH", "CRITICAL",
    name="ticket_priority",
    create_type=False,
)

ticket_status_enum = postgresql.ENUM(
    "OPEN", "IN_PROGRESS", "WAITING_FOR_CUSTOMER", "RESOLVED", "CLOSED",
    name="ticket_status",
    create_type=False,
)

message_type_enum = postgresql.ENUM(
    "CUSTOMER_REPLY", "AGENT_REPLY",
    name="message_type",
    create_type=False,
)

revision_type_enum = postgresql.ENUM(
    "EDIT", "SOFT_DELETE",
    name="revision_type",
    create_type=False,
)

upload_status_enum = postgresql.ENUM(
    "PENDING", "UPLOADED", "FAILED", "EXPIRED",
    name="upload_status",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    customer_urgency_enum.create(bind, checkfirst=True)
    ticket_priority_enum.create(bind, checkfirst=True)
    ticket_status_enum.create(bind, checkfirst=True)
    message_type_enum.create(bind, checkfirst=True)
    revision_type_enum.create(bind, checkfirst=True)
    upload_status_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('primary_category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('customer_urgency', customer_urgency_enum, nullable=False),
    sa.Column('priority', ticket_priority_enum, nullable=False),
    sa.Column('status', ticket_status_enum, nullable=False),
    sa.Column('conversation_version', sa.Integer(), nullable=False),
    sa.Column('conversation_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.user_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.user_id'], ),
    sa.ForeignKeyConstraint(['primary_category_id'], ['ticket_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_agent_id'), 'tickets', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_last_message_at'), 'tickets', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_tickets_primary_category_id'), 'tickets', ['primary_category_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('internal_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notes_ticket_id'), 'internal_notes', ['ticket_id'], unique=False)
    op.create_table('ticket_assignment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=True),
    sa.Column('to_agent_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_assignment_history_ticket_id'), 'ticket_assignment_history', ['ticket_id'], unique=False)
    op.create_table('ticket_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_audit_events_event_type'), 'ticket_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ticket_audit_events_ticket_id'), 'ticket_audit_events', ['ticket_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('message_type', message_type_enum, nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('ticket_priority_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('old_priority', ticket_priority_enum , nullable=False),
    sa.Column('new_priority', ticket_priority_enum, nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_priority_history_ticket_id'), 'ticket_priority_history', ['ticket_id'], unique=False)
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    op.create_table('message_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('previous_body', sa.Text(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('change_type', revision_type_enum, nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_revisions_message_id'), 'message_revisions', ['message_id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('upload_status', upload_status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_ticket_attachments_message_id'), 'ticket_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_attachments_message_id'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_message_revisions_message_id'), table_name='message_revisions')
    op.drop_table('message_revisions')
    op.drop_table('ticket_tags')
    op.drop_index(op.f('ix_ticket_priority_history_ticket_id'), table_name='ticket_priority_history')
    op.drop_table('ticket_priority_history')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_ticket_audit_events_ticket_id'), table_name='ticket_audit_events')
    op.drop_index(op.f('ix_ticket_audit_events_event_type'), table_name='ticket_audit_events')
    op.drop_table('ticket_audit_events')
    op.drop_index(op.f('ix_ticket_assignment_history_ticket_id'), table_name='ticket_assignment_history')
    op.drop_table('ticket_assignment_history')
    op.drop_index(op.f('ix_internal_notes_ticket_id'), table_name='internal_notes')
    op.drop_table('internal_notes')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_primary_category_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_last_message_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_agent_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('ticket_categories')
    op.drop_table('tags')
    bind = op.get_bind()

    upload_status_enum.drop(bind, checkfirst=True)
    revision_type_enum.drop(bind, checkfirst=True)
    message_type_enum.drop(bind, checkfirst=True)
    ticket_status_enum.drop(bind, checkfirst=True)
    ticket_priority_enum.drop(bind, checkfirst=True)
    customer_urgency_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
